### PR TITLE
Add native materialized views

### PR DESCRIPTION
**Pull request by rod-glover**
Add the following materialized views defined using native (direct) support in PostgreSQL >= 9.3:

- `vars_per_history_mv`
- `station_obs_stats_mv`
- `collapsed_vars_mv`
- `obs_count_per_month_history_mv`
- `climo_obs_count_mv`

Additionally add some documentation of this and of the previous manually maintained matviews.

### CODE REVIEW

**Review by jameshiebert — COMMENTED** [review]
Are you intending these scripts for *reference* or for usage? If the latter, I have a few concerns:

1. Explicitly using the `crmp.` schema when creating the matviews doesn't allow for any flexibility in database administration (w.r.t. schemas and roles). A more flexible approach is to leave it implicit and let the schema be determined by the default path of the user that's creating the matviews.
1. Likewise, explicitly granting permissions to specific users (e.g. `metnorth_ro`) is database instance specific and shouldn't be included here IMO. E.g. this will fail when go to run it on `dbmsc` or `crmp`.
1. Likewise with the use of `TABLESPACE`s. These tables spaces may or may not exist, given an arbitrary database connection.
1. You say that the definition doesn't match up w/ what's in `../matvies`. Do they match up with the ORM definitions? If not, we won't be able to actually use them from our Python code...

**Comment by rod-glover** [comment]
@jameshiebert , I've renamed `database/matviews` to `database/manual-matviews`. Is there any reason this would cause problems? I can see none.

**Comment by jameshiebert** [comment]
No, that seems fine.

**Comment by rod-glover** [comment]
I am intending these scripts for reference. They document what I *did*. Furthermore, PyCDS should stand in the place of these scripts, although there will be a gap between now and the time that PyCDS has been so updated.

Nevertheless your comments are important.

1. Will remove explicit schema.
1. Will remove permissions.
1. Will remove tablespaces.
1. They match up with the ORM definitions where they exist. (There are none for tables `collapsed_vars_mv` and `station_obs_stats_mv`.) Also, their definitions were copied directly from the views that define the manual matviews in crmp. I've verified both these assertions several times. And finally, I am already using them from Python code without problems.

One additional note: `PyCDS` does not fully define these "manual matviews". It defines classes for 3 of the manual matview tables, but it does not define the other manual matview machinery: not the matviews table, not the views, not the functions, and not the triggers.

When I added materialized views to support the Weather Anomaly project, I did it within PyCDS (see `pycds/weather_anomaly`), but those materialized views and the older ones being treated here are separate.

**Comment by rod-glover** [comment]
@jameshiebert , better?

**Comment by jameshiebert** [comment]
There are still the ownership statements:

`ALTER TABLE [tablename] OWNER`

Are those necessary?

**Comment by rod-glover** [comment]
No; my oversight.

**Comment by rod-glover** [comment]
@jameshiebert , LGTY?

**Comment by jameshiebert** [comment]
Yep, looks great.

**Pull request merged**
